#!/bin/bash

wdir="$DIR/$(date +%Y-%m-%d)"
mkdir -p $wdir
cd $wdir
filename="$(date +%Y-%m-%d_%H.%M)_mc-server"

tar -cz -C $PARENT_DIR $DIR_TO_ENCRYPT/ | gpg -r $GPGKEY --encrypt | (pv -p --timer --rate --bytes > ./$filename.tgz.gpg)
