#!/usr/bin/env bash

sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function message {
    printf "Error: missing arguments. Please include <Current-VM-ID> <Startup-VM-ID>\n"
}

# Check if the two VM IDs are provided, and that they are numbers
if [[ ! "$1" =~ ^[0-9]+$ ]] || [[ ! "$2" =~ ^[0-9]+$ ]] || [ $# != 2 ]
then
    message
    exit 1
fi

VM1=$1
VM2=$2

# Wait until VM1 is stopped before moving on
while [[ -z $(qm status $VM1 | grep -in "stopped") ]]; do
    sleep 1
done

qm start $VM2

exit 0